<?php

/**
 * BaseMaterialType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $image
 * @property Doctrine_Collection $Material
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getImage()                 Returns the current record's "image" value
 * @method Doctrine_Collection getMaterialType()          Returns the current record's "MaterialType" collection
 * @method Doctrine_Collection getFurnitureMaterialType() Returns the current record's "FurnitureMaterialType" collection
 * @method Doctrine_Collection getMaterial()              Returns the current record's "Material" collection
 * @method MaterialType        setId()                    Sets the current record's "id" value
 * @method MaterialType        setName()                  Sets the current record's "name" value
 * @method MaterialType        setDescription()           Sets the current record's "description" value
 * @method MaterialType        setImage()                 Sets the current record's "image" value
 * @method MaterialType        setMaterialType()          Sets the current record's "MaterialType" collection
 * @method MaterialType        setFurnitureMaterialType() Sets the current record's "FurnitureMaterialType" collection
 * @method MaterialType        setMaterial()              Sets the current record's "Material" collectionType
 * @property Doctrine_Collection $FurnitureMaterialType
 * @property Doctrine_Collection $Material
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getImage()                 Returns the current record's "image" value
 * @method Doctrine_Collection getMaterialType()          Returns the current record's "MaterialType" collection
 * @method Doctrine_Collection getFurnitureMaterialType() Returns the current record's "FurnitureMaterialType" collection
 * @method Doctrine_Collection getMaterial()              Returns the current record's "Material" collection
 * @method MaterialType        setId()                    Sets the current record's "id" value
 * @method MaterialType        setName()                  Sets the current record's "name" value
 * @method MaterialType        setDescription()           Sets the current record's "description" value
 * @method MaterialType        setImage()                 Sets the current record's "image" value
 * @method MaterialType        setMaterialType()          Sets the current record's "MaterialType" collection
 * @method MaterialType        setFurnitureMaterialType() Sets the current record's "FurnitureMaterialType" collection
 * @method MaterialType        setMaterial()              Sets the current record's "Material" collection
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterialType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('material_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2047, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2047,
             ));
        $this->hasColumn('image', 'string', 511, array(
             'type' => 'string',
             'notnull' => false,
             'default' => 'default_material_type.png',
             'length' => 511,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Furniture as MaterialType', array(
             'refClass' => 'FurnitureMaterialType',
             'local' => 'material_type_id',
             'foreign' => 'furniture_id'));

        $this->hasMany('FurnitureMaterialType', array(
             'local' => 'id',
             'foreign' => 'material_type_id'));

        $this->hasMany('Material', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}