<?php

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $RoomFurnitureType
 * @property Doctrine_Collection $FurnitureType
 * @property Doctrine_Collection $Portfolio
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getRoomFurnitureType() Returns the current record's "RoomFurnitureType" collection
 * @method Doctrine_Collection getFurnitureType()     Returns the current record's "FurnitureType" collection
 * @method Doctrine_Collection getPortfolio()         Returns the current record's "Portfolio" collection
 * @method Room                setId()                Sets the current record's "id" value
 * @method Room                setName()              Sets the current record's "name" value
 * @method Room                setRoomFurnitureType() Sets the current record's "RoomFurnitureType" collection
 * @method Room                setFurnitureType()     Sets the current record's "FurnitureType" collection
 * @method Room                setPortfolio()         Sets the current record's "Portfolio" collection
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RoomFurnitureType', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $this->hasMany('FurnitureType', array(
             'refClass' => 'RoomFurnitureType',
             'local' => 'room_id',
             'foreign' => 'furniture_type_id'));

        $this->hasMany('Portfolio', array(
             'local' => 'id',
             'foreign' => 'room_id'));
    }
}