<?php

/**
 * BaseMaterialPreorder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $material_id
 * @property integer $preorder_id
 * @property Material $Material
 * @property Preorder $Preorder
 * 
 * @method integer          getMaterialId()  Returns the current record's "material_id" value
 * @method integer          getPreorderId()  Returns the current record's "preorder_id" value
 * @method Material         getMaterial()    Returns the current record's "Material" value
 * @method Preorder         getPreorder()    Returns the current record's "Preorder" value
 * @method MaterialPreorder setMaterialId()  Sets the current record's "material_id" value
 * @method MaterialPreorder setPreorderId()  Sets the current record's "preorder_id" value
 * @method MaterialPreorder setMaterial()    Sets the current record's "Material" value
 * @method MaterialPreorder setPreorder()    Sets the current record's "Preorder" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterialPreorder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('material_preorder');
        $this->hasColumn('material_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('preorder_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Material', array(
             'local' => 'material_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Preorder', array(
             'local' => 'preorder_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}