<?php

/**
 * BaseFurnitureMaterial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $furniture_id
 * @property integer $material_id
 * @property Furniture $Furniture
 * @property Material $Material
 * 
 * @method integer           getFurnitureId()  Returns the current record's "furniture_id" value
 * @method integer           getMaterialId()   Returns the current record's "material_id" value
 * @method Furniture         getFurniture()    Returns the current record's "Furniture" value
 * @method Material          getMaterial()     Returns the current record's "Material" value
 * @method FurnitureMaterial setFurnitureId()  Sets the current record's "furniture_id" value
 * @method FurnitureMaterial setMaterialId()   Sets the current record's "material_id" value
 * @method FurnitureMaterial setFurniture()    Sets the current record's "Furniture" value
 * @method FurnitureMaterial setMaterial()     Sets the current record's "Material" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFurnitureMaterial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('furniture_material');
        $this->hasColumn('furniture_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('material_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Furniture', array(
             'local' => 'furniture_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Material', array(
             'local' => 'material_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}