<?php

/**
 * BaseRoomFurnitureType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $room_id
 * @property integer $furniture_type_id
 * @property Room $Room
 * @property FurnitureType $FurnitureType
 * 
 * @method integer           getRoomId()            Returns the current record's "room_id" value
 * @method integer           getFurnitureTypeId()   Returns the current record's "furniture_type_id" value
 * @method Room              getRoom()              Returns the current record's "Room" value
 * @method FurnitureType     getFurnitureType()     Returns the current record's "FurnitureType" value
 * @method RoomFurnitureType setRoomId()            Sets the current record's "room_id" value
 * @method RoomFurnitureType setFurnitureTypeId()   Sets the current record's "furniture_type_id" value
 * @method RoomFurnitureType setRoom()              Sets the current record's "Room" value
 * @method RoomFurnitureType setFurnitureType()     Sets the current record's "FurnitureType" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoomFurnitureType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_furniture_type');
        $this->hasColumn('room_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('furniture_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Room', array(
             'local' => 'room_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FurnitureType', array(
             'local' => 'furniture_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}