<?php

/**
 * BaseFurniturePreorder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $furniture_id
 * @property integer $preorder_id
 * @property Furniture $Furniture
 * @property Preorder $Preorder
 * 
 * @method integer           getFurnitureId()  Returns the current record's "furniture_id" value
 * @method integer           getPreorderId()   Returns the current record's "preorder_id" value
 * @method Furniture         getFurniture()    Returns the current record's "Furniture" value
 * @method Preorder          getPreorder()     Returns the current record's "Preorder" value
 * @method FurniturePreorder setFurnitureId()  Sets the current record's "furniture_id" value
 * @method FurniturePreorder setPreorderId()   Sets the current record's "preorder_id" value
 * @method FurniturePreorder setFurniture()    Sets the current record's "Furniture" value
 * @method FurniturePreorder setPreorder()     Sets the current record's "Preorder" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFurniturePreorder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('furniture_preorder');
        $this->hasColumn('furniture_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('preorder_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Furniture', array(
             'local' => 'furniture_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Preorder', array(
             'local' => 'preorder_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}