<?php

/**
 * BasePortfolioPreorder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $portfolio_id
 * @property integer $preorder_id
 * @property Portfolio $Portfolio
 * @property Preorder $Preorder
 * 
 * @method integer           getPortfolioId()  Returns the current record's "portfolio_id" value
 * @method integer           getPreorderId()   Returns the current record's "preorder_id" value
 * @method Portfolio         getPortfolio()    Returns the current record's "Portfolio" value
 * @method Preorder          getPreorder()     Returns the current record's "Preorder" value
 * @method PortfolioPreorder setPortfolioId()  Sets the current record's "portfolio_id" value
 * @method PortfolioPreorder setPreorderId()   Sets the current record's "preorder_id" value
 * @method PortfolioPreorder setPortfolio()    Sets the current record's "Portfolio" value
 * @method PortfolioPreorder setPreorder()     Sets the current record's "Preorder" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePortfolioPreorder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('portfolio_preorder');
        $this->hasColumn('portfolio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('preorder_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Portfolio', array(
             'local' => 'portfolio_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Preorder', array(
             'local' => 'preorder_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}