<?php

/**
 * BaseFurnitureMaterialType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $furniture_id
 * @property integer $material_type_id
 * @property Furniture $Furniture
 * @property MaterialType $MaterialType
 * 
 * @method integer               getFurnitureId()      Returns the current record's "furniture_id" value
 * @method integer               getMaterialTypeId()   Returns the current record's "material_type_id" value
 * @method Furniture             getFurniture()        Returns the current record's "Furniture" value
 * @method MaterialType          getMaterialType()     Returns the current record's "MaterialType" value
 * @method FurnitureMaterialType setFurnitureId()      Sets the current record's "furniture_id" value
 * @method FurnitureMaterialType setMaterialTypeId()   Sets the current record's "material_type_id" value
 * @method FurnitureMaterialType setFurniture()        Sets the current record's "Furniture" value
 * @method FurnitureMaterialType setMaterialType()     Sets the current record's "MaterialType" value
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFurnitureMaterialType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('furniture_material_type');
        $this->hasColumn('furniture_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('material_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Furniture', array(
             'local' => 'furniture_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MaterialType', array(
             'local' => 'material_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}