<?php

/**
 * BaseFurnitureType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property Doctrine_Collection $Room
 * @property Doctrine_Collection $RoomFurnitureType
 * @property Doctrine_Collection $Furniture
 * @property Doctrine_Collection $FurniturePortfolio
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getImage()              Returns the current record's "image" value
 * @method Doctrine_Collection getRoom()               Returns the current record's "Room" collection
 * @method Doctrine_Collection getRoomFurnitureType()  Returns the current record's "RoomFurnitureType" collection
 * @method Doctrine_Collection getFurniture()          Returns the current record's "Furniture" collection
 * @method Doctrine_Collection getFurniturePortfolio() Returns the current record's "FurniturePortfolio" collection
 * @method FurnitureType       setId()                 Sets the current record's "id" value
 * @method FurnitureType       setName()               Sets the current record's "name" value
 * @method FurnitureType       setImage()              Sets the current record's "image" value
 * @method FurnitureType       setRoom()               Sets the current record's "Room" collection
 * @method FurnitureType       setRoomFurnitureType()  Sets the current record's "RoomFurnitureType" collection
 * @method FurnitureType       setFurniture()          Sets the current record's "Furniture" collection
 * @method FurnitureType       setFurniturePortfolio() Sets the current record's "FurniturePortfolio" collection
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFurnitureType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('furniture_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 511, array(
             'type' => 'string',
             'notnull' => false,
             'default' => 'default_furn_type.png',
             'length' => 511,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Room', array(
             'refClass' => 'RoomFurnitureType',
             'local' => 'furniture_type_id',
             'foreign' => 'room_id'));

        $this->hasMany('RoomFurnitureType', array(
             'local' => 'id',
             'foreign' => 'furniture_type_id'));

        $this->hasMany('Furniture', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('FurniturePortfolio', array(
             'local' => 'id',
             'foreign' => 'furniture_id'));
    }
}