quantity_unit:
  class: sfDoctrineRouteCollection
  options:
    model:                QuantityUnit
    module:               quantity_unit
    prefix_path:          /quantity_unit
    column:               id
    with_wildcard_routes: true

room:
  class: sfDoctrineRouteCollection
  options:
    model:                Room
    module:               room
    prefix_path:          /room
    column:               id
    with_wildcard_routes: true

preorder:
  class: sfDoctrineRouteCollection
  options:
    model:                Preorder
    module:               preorder
    prefix_path:          /preorder
    column:               id
    with_wildcard_routes: true

preorder_show:
  url: /prorder/:id
  class: sfDoctrineRoute
  options: { model: Preorder, type: object, method_for_query: getFullPreorder }
  params:  { module: preorder, action: ListShow }

portfolio:
  class: sfDoctrineRouteCollection
  options:
    model:                Portfolio
    module:               portfolio
    prefix_path:          /portfolio
    column:               id
    with_wildcard_routes: true

material_type:
  class: sfDoctrineRouteCollection
  options:
    model:                MaterialType
    module:               material_type
    prefix_path:          /material_type
    column:               id
    with_wildcard_routes: true

material:
  class: sfDoctrineRouteCollection
  options:
    model:                Material
    module:               material
    prefix_path:          /material
    column:               id
    with_wildcard_routes: true

furniture_type:
  class: sfDoctrineRouteCollection
  options:
    model:                FurnitureType
    module:               furniture_type
    prefix_path:          /furniture_type
    column:               id
    with_wildcard_routes: true

furniture:
  class: sfDoctrineRouteCollection
  options:
    model:                Furniture
    module:               furniture
    prefix_path:          /furniture
    column:               id
    with_wildcard_routes: true

logout:
  url:    /signout
  params: { module: sfGuardAuth, action: signout }

homepage:
  url:   /
  param: { module: furniture, action: index }