generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Material
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          material
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:       ~
      fields:
        Type:        { label: 'Вид' }
        name:        { label: 'Название' }
        description: { label: 'Описание' }
        image:       { label: 'Картинка' }
      list:
        title:   'Материалы'
        display: [Type, image, name, description]
      filter:
        display: [type_id, name, description, furniture_list]
      form:    ~
      edit:
        title: 'Редактирование материала'
      new:
        title: 'Создание нового материала'
