<?php

/**
 * FurniturePortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurniturePortfolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurniturePortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FurniturePortfolio');
    }
}