<?php

/**
 * FurnitureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurnitureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurnitureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Furniture');
    }
    
    /**
     * 
     * Функция для роутинга, возвращающая мебель
     * с присоединенными данными
     * @param unknown_type $q
     */
    public function getFurniture(Doctrine_Query $q)
    {
      $alias = $q->getRootAlias();
      $q->leftJoin($alias.'.Material m')
        ->leftJoin($alias.'.Type t')
        ->leftJoin($alias.'.Portfolio p');
      
      $furniture = $q->fetchOne();
      $q->free();
      
      return $furniture;
    }
    
    /**
     * 
     * Функция возвращающая массив мебели, по заданному
     * списку идентификаторов
     * @param unknown_type $ids
     */
    public function getFurnitureByIds($ids)
    {
      $q = $this->createQuery('f')
                ->whereIn('f.id', $ids)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
                
      $furn = $q->execute();
      $q->free();
      
      return $furn;
    }
}