<?php

/**
 * FurnitureMaterialTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurnitureMaterialTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurnitureMaterialTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FurnitureMaterialType');
    }
}