<?php

/**
 * FurniturePreorderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurniturePreorderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurniturePreorderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FurniturePreorder');
    }
}