<?php

/**
 * FurnitureMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurnitureMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurnitureMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FurnitureMaterial');
    }
}