<?php

/**
 * FurnitureTypePortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FurnitureTypePortfolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FurnitureTypePortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FurnitureTypePortfolio');
    }
}