<?php

/**
 * MaterialTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialType');
    }
    
    public function getTypeMaterials($type_id)
    {
      $q = Doctrine_Query::create()->select('m.*')
                                   ->from('Material m')
                                   ->where('m.type_id = ?', $type_id);
      
      return $q;
    }
}