<?php

/**
 * MaterialTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialType');
    }
    
    public function getTypeMaterials(Doctrine_Query $q)
    {
      $alias = $q->getRootAlias();
      $q->leftJoin($alias.'.Material m');
      
      $material = $q->fetchOne();
      $q->free();
      
      return $material;
    }
}