<?php

/**
 * MaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Material');
    }
    
    public function getMaterial(Doctrine_Query $q)
    {
      $alias = $q->getRootAlias();
      $q->leftJoin($alias.'.Type t')
        ->leftJoin($alias.'.Furniture f');
      $material = $q->fetchOne();
      $q->free();
      
      return $material;
    }
}