<?php

/**
 * MaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Material');
    }
    
    public function getMaterial(Doctrine_Query $q)
    {
      $alias = $q->getRootAlias();
      $q->leftJoin($alias.'.Type t')
        ->leftJoin($alias.'.Furniture f');
      $material = $q->fetchOne();
      $q->free();
      
      return $material;
    }
    
    /**
     * 
     * Функция возвращающая массив материалов, по заданному
     * списку идентификаторов
     * @param unknown_type $ids
     */
    public function getMaterialeByIds($ids)
    {
      $q = $this->createQuery('m')
                ->whereIn('m.id', $ids)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
                
      $material = $q->execute();
      $q->free();
      
      return $material;
    }    
}