<?php

/**
 * MaterialType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MaterialType extends BaseMaterialType
{
  public function __toString()
  {
    return $this->getName();
  }  

  public function delete(Doctrine_Connection $con = null)
  {
    $cover = $this->getImage();
    $file = sfConfig::get('sf_upload_dir') . DIRECTORY_SEPARATOR . 'material_type' . DIRECTORY_SEPARATOR . $cover;
    unlink($file);
    
    return parent::delete($con);
  }
}
