<?php

/**
 * PortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortfolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Portfolio');
    }
    
    public function getRoomPortfolio($room_id)
    {
      $q = $this->createQuery('p')
                ->where('p.room_id = ?', $room_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
                
      $portfolio_list = $q->execute();
      $q->free();
      
      return $portfolio_list;
    }
    
    public function getPortfolioList()
    {
      $q = $this->createQuery('p')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
                
      $portfolio_list = $q->execute();
      $q->free();
      
      return $portfolio_list;
    }
    
    public function getPortfolio(Doctrine_Query $q)
    {
      $alias = $q->getRootAlias();
      $q->leftJoin($alias.'.Room r')
        ->leftJoin($alias.'.Furniture f');
        
      $portfolio = $q->fecthOne();
      $q->free();
      
      return $portfolio;
    }
    
    /**
     * 
     * Функция возвращающая массив сделаных работ, по заданному
     * списку идентификаторов
     * @param unknown_type $ids
     */
    public function getPortfolioByIds($ids)
    {
      $q = $this->createQuery('p')
                ->whereIn('p.id', $ids)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
                
      $portfolio = $q->execute();
      $q->free();
      
      return $portfolio;
    }      
}