<?php

/**
 * PortfolioPreorderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortfolioPreorderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PortfolioPreorderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PortfolioPreorder');
    }
}