<?php

/**
 * Portfolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    proff.dev
 * @subpackage model
 * @author     Лесникова Екатерина
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Portfolio extends BasePortfolio
{
  public function __toString()
  {
    return $this->getName();
  }

  public function delete(Doctrine_Connection $con = null)
  {
    $directory = sfConfig::get('sf_upload_dir') . DIRECTORY_SEPARATOR . 'portfolio' . DIRECTORY_SEPARATOR;
    $image = $this->getImage();
    $thumbnail = 'thumb_' . $image;
    $image_file = $directory . $image;
    $thumbnail_file = $directory . $thumbnail;
    unlink($image_file);
    unlink($thumbnail_file);
    
    return parent::delete($con);
  }
}
