<?php

/**
 * PortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortfolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Portfolio');
    }
}