<?php

/**
 * PreorderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreorderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreorderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preorder');
    }
    
    public function getFullPreorder(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();
        
        $q->leftJoin($rootAlias.'.Furniture fr')
          ->leftJoin($rootAlias.'.Material  mt')
          ->leftJoin($rootAlias.'.Portfolio pr');

        return $q->execute();
    }
}