<?php

/**
 * PreorderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreorderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreorderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preorder');
    }
}