<?php

/**
 * QuantityUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuantityUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuantityUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuantityUnit');
    }
}