<?php

/**
 * RoomFurnitureTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomFurnitureTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomFurnitureTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoomFurnitureType');
    }
}