room:
  url:     /room/:id
  class:   sfDoctrineRoute
  options: { model:  Room, type: object }
  param:   { module: room, action: show }

furniture_types: #Все виды мебели
  url:     /furniture/types
  class:   sfDoctrineRoute
  options: { model: FurnitureType, type: list }
  param:   { module: furniture, action: types }

furniture_type:  #Конкретный вид мебели
  url:  /furniture/type/:id
  class: sfDoctrineRoute
  options:  { model: FurnitureType, type: object, method_for_query: getTypeFurniture }
  param:    { module: furniture, action: type }

furniture_show:  #Конкретная мебель
  url:  /furniture/:id
  class: sfDoctrineRoute
  options:  { model: Furniture, type: object, method_for_query: getFurniture }
  param:    { module: furniture, action: show }

material_types: #Все виды материалов
  url:     /material/types
  class:   sfDoctrineRoute
  options: { model:  MaterialType, type: list }
  param:   { module: material, action: types }

material_type:  #Конкретный вид материалов
  url:     /material/type/:id
  class:   sfDoctrineRoute
  options: { model: MaterialType, type: object, method_for_query: getTypeMaterials }
  param:   { module: material , action: type }

material_show:  #Конкретный материал
  url:  /material/:id
  class: sfDoctrineRoute
  options:  { model: Material, type: object, method_for_query: getMaterial }
  param:    { module: material, action: show }

portfolio:
  url:     /portfolio
  class:   sfDoctrineRoute
  options: { model:  Portfolio, type: list }
  param:   { module: portfolio , action: index }

portfolio_show:
  url:     /portfolio/:id
  class:   sfDoctrineRoute
  options: { model:  Portfolio, type: object }
  param:   { module: portfolio, action: show }

about:
  url:   /about
  param: { module: information , action: about }

contacts:
  url:   /contacts
  param: { module: information, action: contacts }
  

#Роутинги пользователя
signin:
  url: /login
  param: { module: user, action: signin }

signout:
  url: /logout
  param: { module: user, action: signout }

register:
  url: /register
  param: { module: registration, action: apply }

password:
  url: /reset_password
  param: { module: user, action: password, wildcard: true }

activation:
  url: /activate/:code
  param: { module: user, action: activate }

homepage:
  url:     /
  class:   sfDoctrineRoute
  options: { model: Room, type: list }
  param:   { module: room, action: index }
