generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Room
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          room
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: 'Название' }
      list:
        title:   'Комнаты'
        display: [=name]
      filter:  ~
      form:    ~
      edit:
        title: 'Редактирование комнаты'
      new:
        title: 'Создание комнаты'
