generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Portfolio
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          portfolio
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:       ~
      fields:
        Room:        { label: 'Комната' }   
        name:        { label: 'Кодовое название' }
        price:       { label: 'Цена'}
        description: { label: 'Описание' }
        image:       { label: 'Фотография' }  
      list:
        title:    'Портфолио'
        display:  [Room, image, name, price, description]
      filter:
        display:  [room_id, name, price, description, date, furniture_list]
      form:    ~
      edit:
        title:  'Редактировать сделанную работу'
      new:
        title:  'Добавить новую сделанную работу'
