generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Portfolio
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          portfolio
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:    { label: "Добавить мебель"}
        _edit:   { label: 'Редактировать' }
        _delete: { label: 'Удалить' }
      fields:
        Room:        { label: 'Комната' }   
        name:        { label: 'Кодовое название' }
        description: { label: 'Описание' }
        image:       { label: 'Фотография' }  
      list:
        title:    'Портфолио'
        display:  [Room, name, description, image]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
