generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FurnitureType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          furniture_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:  { label: 'Название' }
        image: { label: 'Картинка' }
      list:
        title:   'Виды мебели'
        display: [name, image]
      filter:
        display: [name, room_list]
      form:    ~
      edit:
        title: 'Редактирование вида мебели'
      new:
        title: 'Создание нового вида мебели'
