generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MaterialType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          material_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:        { label: 'Название' }
        description: { label: 'Описание' }
        image:       { label: 'Картинка' }
      list:
        title:   'Виды материалов'
        display: [image,  name, description]
      filter:
        display: [name, description]
      form:    ~
      edit:
        title:  'Редактирование вида материалов'
      new:
        title:  'Создание нового типа материалов'
