generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Preorder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          preorder
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        show:   { label:  'Посмотреть' }
        _edit:   { label: 'Редактировать' }
        _delete: { label: 'Удалить' }
      fields:
        id:           { label: 'Номер'}
        first_name:   { label: "Имя"}
        middle_name:  { label: "Фамилия"}
        last_name:    { label: "Отчество"}
        description:  { label: 'Дополнительные пожелания' }
      list:
        title:          'Отправленные черновики'
        display:        [id, first_name, middle_name, last_name ]
        object_actions:
          show:   ~
          _edit:   ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
