generator:
  class: sfDoctrineGenerator
  param:
    model_class:           QuantityUnit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quantity_unit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:        { label: 'Название' }
      list:
        title:   'Единицы измерения'
        display: [name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
