<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('preorder', 'first_name', 'string', '63', array(
             'notnull' => '',
             ));
        $this->changeColumn('preorder', 'middle_name', 'string', '63', array(
             'notnull' => '',
             ));
        $this->changeColumn('preorder', 'last_name', 'string', '63', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}