<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('furniture', 'description', 'string', '2047', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}