<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('furniture', 'furniture_type_id_furniture_type_id');
        $this->dropForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_type_id');
        $this->dropForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_id');
        $this->dropForeignKey('material', 'material_type_id_material_type_id');
        $this->createForeignKey('furniture', 'furniture_type_id_furniture_type_id_1', array(
             'name' => 'furniture_type_id_furniture_type_id_1',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'furniture_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_id_1', array(
             'name' => 'furniture_portfolio_furniture_id_furniture_id_1',
             'local' => 'furniture_id',
             'foreign' => 'id',
             'foreignTable' => 'furniture',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('material', 'material_type_id_material_type_id_1', array(
             'name' => 'material_type_id_material_type_id_1',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'material_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('furniture', 'furniture_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->addIndex('furniture_portfolio', 'furniture_portfolio_furniture_id', array(
             'fields' => 
             array(
              0 => 'furniture_id',
             ),
             ));
        $this->addIndex('material', 'material_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('furniture', 'furniture_type_id_furniture_type_id', array(
             'name' => 'furniture_type_id_furniture_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'furniture_type',
             ));
        $this->createForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_type_id', array(
             'name' => 'furniture_portfolio_furniture_id_furniture_type_id',
             'local' => 'furniture_id',
             'foreign' => 'id',
             'foreignTable' => 'furniture_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_id', array(
             'name' => 'furniture_portfolio_furniture_id_furniture_id',
             'local' => 'furniture_id',
             'foreign' => 'id',
             'foreignTable' => 'furniture',
             ));
        $this->createForeignKey('material', 'material_type_id_material_type_id', array(
             'name' => 'material_type_id_material_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'material_type',
             ));
        $this->dropForeignKey('furniture', 'furniture_type_id_furniture_type_id_1');
        $this->dropForeignKey('furniture_portfolio', 'furniture_portfolio_furniture_id_furniture_id_1');
        $this->dropForeignKey('material', 'material_type_id_material_type_id_1');
        $this->removeIndex('furniture', 'furniture_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->removeIndex('furniture_portfolio', 'furniture_portfolio_furniture_id', array(
             'fields' => 
             array(
              0 => 'furniture_id',
             ),
             ));
        $this->removeIndex('material', 'material_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }
}