<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('quantity_unit', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'text' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '63',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('material', 'quantity_id', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('quantity_unit');
        $this->removeColumn('material', 'quantity_id');
    }
}