<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('furniture', 'price', 'float', '', array(
             'notnull' => '',
             ));
        $this->addColumn('material', 'price', 'float', '', array(
             'notnull' => '',
             ));
        $this->addColumn('portfolio', 'price', 'float', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('furniture', 'price');
        $this->removeColumn('material', 'price');
        $this->removeColumn('portfolio', 'price');
    }
}