<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('material', 'material_quantity_id_quantity_unit_id', array(
             'name' => 'material_quantity_id_quantity_unit_id',
             'local' => 'quantity_id',
             'foreign' => 'id',
             'foreignTable' => 'quantity_unit',
             ));
        $this->addIndex('material', 'material_quantity_id', array(
             'fields' => 
             array(
              0 => 'quantity_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('material', 'material_quantity_id_quantity_unit_id');
        $this->removeIndex('material', 'material_quantity_id', array(
             'fields' => 
             array(
              0 => 'quantity_id',
             ),
             ));
    }
}