generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Furniture
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          furniture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:    { label: "Добавить мебель"}
        _edit:   { label: 'Редактировать' }
        _delete: { label: 'Удалить' }
      fields:
        name:        
          label:    'Наименование'
        description: { label: 'Описание' }
        image:       { label: 'Картинка' }
        Type:        { label: 'Вид'}
      list:
        title:   'Мебель'
        display: [Type, =name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
